name: Update Data

on:
  schedule:
    - cron: "* * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  

    - name: Install dependencies
      run: pip install pandas pymongo requests "hopsworks=3.2.0"

    - name: Run script
      run: python update_data.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update data"
        git push
